apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vdp.apigateway" . }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if eq .Values.updateStrategy.type "Recreate" }}
    rollingUpdate: null
    {{- end }}
  {{- if not .Values.apigateway.autoscaling.enabled }}
  replicas: {{ .Values.apigateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vdp.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        {{- include "vdp.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: api-gateway
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/apigateway/configmap.yaml") . | sha256sum }}
        {{- with .Values.apigateway.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      {{- if .Values.apigateway.serviceAccountName }}
      serviceAccountName: {{ .Values.apigateway.serviceAccountName }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.console.automountServiceAccountToken | default false }}
      terminationGracePeriodSeconds: 120
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-dependencies
          image: curlimages/curl:8.00.1
          command: ['sh', '-c']
          args:
          - >
            while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' ${PIPELINE_BACKEND_HOST}:${PIPELINE_BACKEND_PORT}/v1alpha/health/pipeline)" != "200" ]]; do echo waiting for pipeline-backend; sleep 1; done &&
            while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' ${CONNECTOR_BACKEND_HOST}:${CONNECTOR_BACKEND_PORT}/v1alpha/health/connector)" != "200" ]]; do echo waiting for connector-backend; sleep 1; done &&
            while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' ${MODEL_BACKEND_HOST}:${MODEL_BACKEND_PORT}/v1alpha/health/model)" != "200" ]]; do echo waiting for model-backend; sleep 1; done &&
            while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' ${MGMT_BACKEND_HOST}:${MGMT_BACKEND_PORT}/v1alpha/health/mgmt)" != "200" ]]; do echo waiting for mgmt-backend; sleep 1; done &&
            while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' ${INFLUXDB_HOST}:${INFLUXDB_PORT}/health)" != "200" ]]; do echo waiting for influxdb; sleep 1; done
          env:
            - name: PIPELINE_BACKEND_HOST
              value: "{{ template "vdp.pipeline" . }}"
            - name: PIPELINE_BACKEND_PORT
              value: "{{ template "vdp.pipeline.publicPort" . }}"
            - name: CONNECTOR_BACKEND_HOST
              value: "{{ template "vdp.connector" . }}"
            - name: CONNECTOR_BACKEND_PORT
              value: "{{ template "vdp.connector.publicPort" . }}"
            - name: MODEL_BACKEND_HOST
              value: "{{ template "vdp.model" . }}"
            - name: MODEL_BACKEND_PORT
              value: "{{ template "vdp.model.publicPort" . }}"
            - name: MGMT_BACKEND_HOST
              value: "{{ template "vdp.mgmt" . }}"
            - name: MGMT_BACKEND_PORT
              value: "{{ template "vdp.mgmt.publicPort" . }}"
            - name: INFLUXDB_HOST
              value: "{{ template "vdp.influxdb" . }}"
            - name: INFLUXDB_PORT
              value: "{{ template "vdp.influxdb.port" . }}"
        {{- with .Values.apigateway.extraInitContainers }}
        {{- toYaml . | indent 8 }}
        {{- end }}
      containers:
        - name: api-gateway
          image: {{ .Values.apigateway.image.repository }}:{{ .Values.apigateway.image.tag }}
          imagePullPolicy: {{ .Values.apigateway.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /__health
              scheme: {{ upper (ternary "https" "http" .Values.apigateway.tls.enabled) }}
              port: {{ ternary "https" "http" .Values.apigateway.tls.enabled }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /__health
              scheme: {{ upper (ternary "https" "http" .Values.apigateway.tls.enabled) }}
              port: {{ ternary "https" "http" .Values.apigateway.tls.enabled }}
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- if .Values.apigateway.resources }}
          resources:
            {{- toYaml .Values.apigateway.resources | nindent 12 }}
          {{- end }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              make config && \
              krakend run \
            {{- if (eq (.Values.logLevel | upper) "DEBUG") }}
              --debug \
            {{- end }}
              --config krakend.json
          ports:
            - name: {{ ternary "https" "http" .Values.apigateway.tls.enabled }}
              containerPort: {{ template "vdp.apigateway.httpPort" . }}
              protocol: TCP
            - name: stats
              containerPort: {{ template "vdp.apigateway.statsPort" . }}
              protocol: TCP
            - name: metrics
              containerPort: {{ template "vdp.apigateway.metricsPort" . }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: {{ .Values.apigateway.configPath }}
              subPath: ".env"
            {{- if .Values.apigateway.tls.enabled }}
            - name: {{ .Values.apigateway.tls.secretName }}
              mountPath: "/etc/vdp/ssl/api-gateway"
              readOnly: true
            {{- end }}
            {{- with .Values.apigateway.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.apigateway.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.apigateway.sidecarContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "vdp.apigateway" . }}
        {{- if .Values.apigateway.tls.enabled }}
        - name: vdp-apigateway-internal-tls
          secret:
            secretName: {{ template "vdp.internalTLS.apigateway.secretName" . }}
            items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
        {{- end }}
        {{- with .Values.apigateway.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.apigateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apigateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apigateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
