{{- if eq .Values.expose.type "ingress" }}
{{- $ingress := .Values.expose.ingress -}}
{{- $tls := .Values.expose.tls -}}
{{- if eq $ingress.controller "gce" }}
{{- $_ := set . "rootPath" "/*" -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: vdp
spec:
  timeoutSec: 60
{{- else }}
{{- $_ := set . "rootPath" "/" -}}
{{- end }}
---
{{- if semverCompare "<1.14-0" (include "vdp.ingress.kubeVersion" .) }}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.19-0" (include "vdp.ingress.kubeVersion" .) }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: "{{ template "vdp.apigateway" . }}"
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
    {{- with $ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if $ingress.className }}
  ingressClassName: {{ $ingress.className }}
  {{- end }}
  {{- if $tls.enabled }}
  tls:
  - secretName: {{ $tls.secret.secretName }}
    {{- if $ingress.hosts.apigateway }}
    hosts:
    - {{ $ingress.hosts.apigateway }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
{{- if semverCompare "<1.19-0" (include "vdp.ingress.kubeVersion" .) }}
      - path: {{ .rootPath }}
        backend:
          serviceName: {{ template "vdp.apigateway" . }}
          servicePort: {{ template "vdp.apigateway.httpPort" . }}
{{- else }}
      - path: {{ .rootPath }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "vdp.apigateway" . }}
            port:
              number: {{ template "vdp.apigateway.httpPort" . }}
{{- end }}
    {{- if $ingress.hosts.apigateway }}
    host: {{ $ingress.hosts.apigateway }}
    {{- end }}
{{- end }}
