apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vdp.connector" . }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: connector
data:
  config.yaml: |+
    server:
      privateport: {{ template "vdp.connector.privatePort" . }}
      publicport: {{ template "vdp.connector.publicPort" . }}
      edition: {{ .Values.edition }}
      usageenabled: {{ .Values.usageEnabled }}
      debug: {{ ternary "true" "false" (eq (.Values.logLevel | upper) "DEBUG") }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/connector/tls.crt
        key: /etc/vdp/ssl/connector/tls.key
      {{- end }}
    container:
      mountsource:
        vdp: /vdp
        airbyte: /airbyte
      mounttarget:
        vdp: /vdp
        airbyte: /local
    database:
      username: {{ default (include "vdp.database.username" .) .Values.database.external.username }}
      password: {{ default (include "vdp.database.rawPassword" .) .Values.database.external.password }}
      host: {{ default (include "vdp.database.host" .) .Values.database.external.host }}
      port: {{ default (include "vdp.database.port" .) .Values.database.external.port }}
      name: connector
      version: {{ .Values.connector.dbVersion }}
      timezone: Etc/UTC
      pool:
        idleconnections: {{ .Values.database.maxIdleConns }}
        maxconnections: {{ .Values.database.maxOpenConns }}
        connlifetime: {{ .Values.database.maxConnLifeTime }}
    cache:
      redis:
        redisoptions:
          addr: {{ default (include "vdp.redis.addr" .) .Values.redis.external.addr }}
    pipelinebackend:
      host: {{ template "vdp.pipeline" . }}
      publicport: {{ template "vdp.pipeline.publicPort" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/pipeline/tls.crt
        key: /etc/vdp/ssl/pipeline/tls.key
      {{- end }}
    mgmtbackend:
      host: {{ template "vdp.mgmt" . }}
      privateport: {{ template "vdp.mgmt.privatePort" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/mgmt/tls.crt
        key: /etc/vdp/ssl/mgmt/tls.key
      {{- end }}
    controller:
      host: {{ template "vdp.controller" . }}
      privateport: {{ template "vdp.controller.privatePort" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/controller/tls.crt
        key: /etc/vdp/ssl/controller/tls.key
      {{- end }}
    usageserver:
      {{- toYaml .Values.usageServer | nindent 6 }}
    log:
      external: {{ .Values.tags.observability }}
      otelcollector:
        host: {{ template "vdp.otel" . }}
        port: {{ template "vdp.otel.port" . }}
