apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vdp.model" . }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: model
data:
  config.yaml: |+
    server:
      port: {{ template "vdp.model.port" . }}
      edition: {{ template "vdp.edition" . }}
      disableusage: {{ .Values.disableUsage }}
      debug: {{ ternary "true" "false" (eq .Values.logLevel "debug") }}
      maximagesize: {{ .Values.maxDataSizeMB }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/model/tls.crt
        key: /etc/vdp/ssl/model/tls.key
      {{- end }}
    pipelinebackend:
      host: {{ template "vdp.pipeline" . }}
      port: {{ template "vdp.pipeline.port" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/pipeline/tls.crt
        key: /etc/vdp/ssl/pipeline/tls.key
      {{- end }}
    mgmtbackend:
      host: {{ template "vdp.mgmt" . }}
      port: {{ template "vdp.mgmt.port" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/mgmt/tls.crt
        key: /etc/vdp/ssl/mgmt/tls.key
      {{- end }}
    usageserver:
      {{- toYaml .Values.usageServer | nindent 6 }}
    tritonserver:
      grpcuri: triton-server:8001
      modelstore: /model-repository
    database:
      username: {{ template "vdp.database.username" . }}
      password: {{ template "vdp.database.rawPassword" . }}
      host: {{ template "vdp.database.host" . }}
      port: {{ template "vdp.database.port" . }}
      name: model
      version: 1
      timezone: Etc/UTC
      pool:
        idleconnections: {{ .Values.database.maxIdleConns }}
        maxconnections: {{ .Values.database.maxOpenConns }}
        connlifetime: {{ .Values.database.maxConnLifeTime }}
    cache:
      redis:
        redisoptions:
          addr: {{ template "vdp.redis.addr" . }}
    maxbatchsizelimitation:
      unspecified: 2
      classification: 16
      detection: 8
      keypoint: 8
      ocr: 2
      instancesegmentation: 8
      semanticsegmentation: 8
    temporal:
      clientoptions:
        hostport: {{ template "vdp.temporal" . }}-frontend-headless:{{ template "vdp.temporal.frontend.grpcPort" . }}
