{{- if and .Values.temporal.enabled .Values.temporal.admintools.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vdp.temporal.admintools" . }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-admintools
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vdp.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: temporal-admintools
  template:
    metadata:
      labels:
        {{- include "vdp.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: temporal-admintools
      {{- with $.Values.temporal.admintools.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.temporal.ui.serviceAccountName }}
      serviceAccountName: {{ .Values.temporal.ui.serviceAccountName }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.temporal.ui.automountServiceAccountToken | default false }}
      terminationGracePeriodSeconds: 120
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- if .Values.database.enabled }}
        - name: wait-for-db
          image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
          imagePullPolicy: {{ $.Values.database.image.pullPolicy }}
          command: ['sh', '-c', "until pg_isready; do echo waiting for db; sleep 2; done"]
          env:
          - name: PGHOST
            value: {{ template "vdp.database" . }}
          - name: PGUSER
            value: {{ template "vdp.database.username" . }}
      {{- end }}
      containers:
        - name: temporal-admin-tools
          image: {{ .Values.temporal.admintools.image.repository }}:{{ .Values.temporal.admintools.image.tag }}
          imagePullPolicy: {{ .Values.temporal.admintools.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
              - ls
              - /
            initialDelaySeconds: 5
            periodSeconds: 5
          command: ["/bin/bash", "-c"]
          args:
            - >
              if ! psql -h ${SQL_HOST} -p $SQL_PORT} -U ${SQL_USER} -W ${SQL_PASSWORD} -c "SELECT datname FROM pg_catalog.pg_database WHERE datname='temporal'" | grep -q "1 row"; then
                SQL_DATABASE=temporal temporal-sql-tool drop -f &&
                SQL_DATABASE=temporal temporal-sql-tool create &&
                SQL_DATABASE=temporal temporal-sql-tool setup -v 0.0 &&
                SQL_DATABASE=temporal temporal-sql-tool update-schema -d schema/postgresql/v96/temporal/versioned &&
                SQL_DATABASE=temporal_visibility temporal-sql-tool drop -f &&
                SQL_DATABASE=temporal_visibility temporal-sql-tool create &&
                SQL_DATABASE=temporal_visibility temporal-sql-tool setup -v 0.0 &&
                SQL_DATABASE=temporal_visibility temporal-sql-tool setup-schema -v 0.0 &&
                SQL_DATABASE=temporal_visibility temporal-sql-tool update -schema-dir schema/postgresql/v96/visibility/versioned
              fi &&
              until tctl cluster health 2>&1 > /dev/null; do echo waiting for Temporal; sleep 2; done &&
              tctl --namespace connector-backend namespace register &&
              tctl --namespace model-backend namespace register &&
              tail -f /dev/null
          ports:
            - name: http
              containerPort: 22
              protocol: TCP
          env:
            - name: TEMPORAL_CLI_ADDRESS
              value: "{{ template "vdp.temporal" . }}-frontend:{{ template "vdp.temporal.frontend.grpcPort" . }}"
            - name:  SQL_PLUGIN
              value: "postgres"
            - name:  SQL_HOST
              value: "{{ template "vdp.database" . }}"
            - name:  SQL_PORT
              value: "{{ template "vdp.database.port" . }}"
            - name:  SQL_USER
              value: "{{ template "vdp.database.username" . }}"
            - name:  SQL_PASSWORD
              value: "{{ template "vdp.database.rawPassword" . }}"
      {{- with .Values.temporal.admintools.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.temporal.admintools.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.temporal.admintools.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
