apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vdp.mgmt" . }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: mgmt
data:
  config.yaml: |+
    server:
      adminport: {{ template "vdp.mgmt.adminPort" . }}
      publicport: {{ template "vdp.mgmt.publicPort" . }}
      edition: {{ template "vdp.edition" . }}
      disableusage: {{ .Values.disableUsage }}
      debug: {{ ternary "true" "false" (eq .Values.logLevel "debug") }}
      maxdatasize: {{ .Values.maxDataSizeMB }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/mgmt/tls.crt
        key: /etc/vdp/ssl/mgmt/tls.key
      {{- end }}
    usageserver:
      {{- toYaml .Values.usageServer | nindent 6 }}
    database:
      username: {{ template "vdp.database.username" . }}
      password: {{ template "vdp.database.rawPassword" . }}
      host: {{ template "vdp.database.host" . }}
      port: {{ template "vdp.database.port" . }}
      name: mgmt
      version: 1
      timezone: Etc/UTC
      pool:
        idleconnections: {{ .Values.database.maxIdleConns }}
        maxconnections: {{ .Values.database.maxOpenConns }}
        connlifetime: {{ .Values.database.maxConnLifeTime }}
