{{- if .Values.pipelineBackend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "vdp.pipelineBackend" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "vdp.pipelineBackend" . }}
    labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: pipeline-backend
  minReplicas: {{ .Values.pipelineBackend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.pipelineBackend.autoscaling.maxReplicas }}
  metrics:
{{- with .Values.pipelineBackend.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- with .Values.pipelineBackend.autoscaling.targetAverageMemoryUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: {{ . }}
{{- end }}
{{- end }}
