blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://discord.gg/sevxWsqpGh
    about: Join our Discord community to ask a question about the project in the #ask-for-help channel
