apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vdp.pipeline" . }}
data:
  config.yaml: |+
    server:
      port: {{ template "vdp.pipeline.port" . }}
      edition: {{ template "vdp.edition" . }}
      disableusage: {{ .Values.disableUsage }}
      debug: {{ ternary "true" "false" (eq .Values.logLevel "debug") }}
      maximagesize: {{ .Values.maxDataSizeMB }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/pipeline/tls.crt
        key: /etc/vdp/ssl/pipeline/tls.key
      {{- end }}
    connectorbackend:
      host: {{ template "vdp.connector" . }}
      port: {{ template "vdp.connector.port" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/connector/tls.crt
        key: /etc/vdp/ssl/connector/tls.key
      {{- end }}
    modelbackend:
      host: {{ template "vdp.model" . }}
      port: {{ template "vdp.model.port" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/model/tls.crt
        key: /etc/vdp/ssl/model/tls.key
      {{- end }}
    mgmtbackend:
      host: {{ template "vdp.mgmt" . }}
      port: {{ template "vdp.mgmt.port" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/mgmt/tls.crt
        key: /etc/vdp/ssl/mgmt/tls.key
      {{- end }}
    usageserver:
      {{- toYaml .Values.usageServer | nindent 6 }}
    database:
      username: {{ template "vdp.database.username" . }}
      password: {{ template "vdp.database.rawPassword" . }}
      host: {{ template "vdp.database.host" . }}
      port: {{ template "vdp.database.port" . }}
      name: pipeline
      version: 1
      timezone: Etc/UTC
      pool:
        idleconnections: {{ .Values.database.maxIdleConns }}
        maxconnections: {{ .Values.database.maxOpenConns }}
        connlifetime: {{ .Values.database.maxConnLifeTime }}
    cache:
      redis:
        redisoptions:
          addr: {{ template "vdp.redis.addr" . }}
    temporal:
      {{- toYaml .Values.temporal | nindent 6 }}
