apiVersion: v2
name: vdp
description: The Helm chart of Instill VDP
type: application
version: 0.1.22-beta #! auto-updated by the CI workflow
appVersion: 0.21.0-beta #! auto-updated by the CI workflow
keywords:
  - unstructured data
  - pipeline
  - ETL/ELT
  - AI
  - Data
sources:
  - https://github.com/instill-ai/vdp
home: "https://www.instill.tech"
icon: https://storage.googleapis.com/public-europe-west2-c-artifacts/imgs/helm-vdp-logo.png
maintainers:
  - name: Instill AI LTD
    url: https://github.com/instill-ai
