{{- if and (eq .Values.temporal.type "internal") .Values.temporal.internal.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vdp.temporal.ui" . }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-ui
spec:
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if eq .Values.updateStrategy.type "Recreate" }}
    rollingUpdate: null
    {{- end }}
  {{- if not .Values.apigateway.autoscaling.enabled }}
  replicas: {{ .Values.apigateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vdp.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: temporal-ui
  template:
    metadata:
      labels:
        {{- include "vdp.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: temporal-ui
      annotations:
        {{- with .Values.temporal.internal.admintools.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.temporal.internal.ui.serviceAccountName }}
      serviceAccountName: {{ .Values.temporal.internal.ui.serviceAccountName }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.temporal.internal.ui.automountServiceAccountToken | default false }}
      terminationGracePeriodSeconds: 120
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: temporal-web
          image: {{ .Values.temporal.internal.ui.image.repository }}:{{ .Values.temporal.internal.ui.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal-frontend.{{ .Release.Namespace }}.svc:{{ template "vdp.temporal.frontend.grpcPort" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.temporal.internal.ui.resources | nindent 12 }}
      {{- with .Values.temporal.internal.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.temporal.internal.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.temporal.internal.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
