global:
  evaluation_interval: 10s
  scrape_interval: 5s
scrape_configs:
  - job_name: "collector"
    static_configs:
      - targets: ["otel-collector:9001", "api-gateway:8071"]
  - job_name: "ray"
    static_configs:
      - targets: ["ray-server:8079"]
  - job_name: "temporalsdkmetrics"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - pipeline-backend:8096
          - pipeline-backend-worker:8096
