{{- if and .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vdp.console" . }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
{{- if eq .Values.expose.type "clusterIP" }}
{{- $clusterIP := .Values.expose.clusterIP }}
  {{- with $clusterIP.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: {{ ternary "https" "http" .Values.internalTLS.enabled }}
      port: {{ default (include "vdp.console.port" .) $clusterIP.ports.console }}
      targetPort: {{ template "vdp.console.port" . }}
{{- else if or (eq .Values.expose.type "ingress") (eq .Values.expose.type "nodePort")}}
{{- $nodePort := .Values.expose.nodePort }}
  {{- with $nodePort.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  ports:
    - name: {{ ternary "https" "http" .Values.internalTLS.enabled }}
      port: {{ default (include "vdp.console.port" .) $nodePort.ports.console.port }}
      targetPort: {{ template "vdp.console.port" . }}
      {{- if and (ge ($nodePort.ports.console.nodePort | int) (30000 | int)) (le ($nodePort.ports.console.nodePort | int) (32767 | int)) }}
      nodePort: {{ $nodePort.ports.console.nodePort }}
      {{- end }}
{{- else if eq .Values.expose.type "loadBalancer" }}
{{- $loadBalancer := .Values.expose.loadBalancer }}
  {{- with $loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  {{- with $loadBalancer.sourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $loadBalancer.IP }}
  loadBalancerIP: {{ $loadBalancer.IP }}
  {{- end }}
  ports:
    - name: {{ ternary "https" "http" .Values.internalTLS.enabled }}
      port: {{ default (include "vdp.console.port" .) $loadBalancer.ports.console }}
      targetPort: {{ template "vdp.console.port" . }}
{{- end }}
  selector:
    {{- include "vdp.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: console
{{- end }}
