apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vdp.model" . }}
  labels:
    {{- include "vdp.labels" . | nindent 4 }}
    app.kubernetes.io/component: model
data:
  config.yaml: |+
    server:
      privateport: {{ template "vdp.model.privatePort" . }}
      publicport: {{ template "vdp.model.publicPort" . }}
      edition: {{ .Values.edition }}
      disableusage: {{ .Values.disableUsage }}
      debug: {{ ternary "true" "false" (eq (.Values.logLevel | upper) "DEBUG") }}
      itmode: {{ .Values.itModeEnabled }}
      maxdatasize: {{ .Values.maxDataSizeMB }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/model/tls.crt
        key: /etc/vdp/ssl/model/tls.key
      {{- end }}
    pipelinebackend:
      host: {{ template "vdp.pipeline" . }}
      publicport: {{ template "vdp.pipeline.publicPort" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/pipeline/tls.crt
        key: /etc/vdp/ssl/pipeline/tls.key
      {{- end }}
    mgmtbackend:
      host: {{ template "vdp.mgmt" . }}
      privateport: {{ template "vdp.mgmt.privatePort" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/mgmt/tls.crt
        key: /etc/vdp/ssl/mgmt/tls.key
      {{- end }}
    controller:
      host: {{ template "vdp.controller" . }}
      privateport: {{ template "vdp.controller.privatePort" . }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/vdp/ssl/controller/tls.crt
        key: /etc/vdp/ssl/controller/tls.key
      {{- end }}
    usageserver:
      {{- toYaml .Values.usageServer | nindent 6 }}
    tritonserver:
      grpcuri: {{ include "vdp.triton" . }}:{{ include "vdp.triton.grpcPort" . }}
      modelstore: /model-repository
    database:
      username: {{ default (include "vdp.database.username" .) .Values.database.external.username }}
      password: {{ default (include "vdp.database.rawPassword" .) .Values.database.external.password }}
      host: {{ default (include "vdp.database.host" .) .Values.database.external.host }}
      port: {{ default (include "vdp.database.port" .) .Values.database.external.port }}
      name: model
      version: {{ .Values.model.dbVersion }}
      timezone: Etc/UTC
      pool:
        idleconnections: {{ .Values.database.maxIdleConns }}
        maxconnections: {{ .Values.database.maxOpenConns }}
        connlifetime: {{ .Values.database.maxConnLifeTime }}
    cache:
      redis:
        redisoptions:
          addr: {{ default (include "vdp.redis.addr" .) .Values.redis.external.addr }}
    maxbatchsizelimitation:
      unspecified: 2
      classification: 16
      detection: 8
      keypoint: 8
      ocr: 2
      instancesegmentation: 8
      semanticsegmentation: 8
      textgeneration: 1
    temporal:
      hostport: {{ default (printf "%s-frontend-headless:%s" (include "vdp.temporal" .) (include "vdp.temporal.frontend.grpcPort" .)) .Values.model.temporal.hostPort }}
      namespace: {{ default "model-backend" .Values.model.temporal.namespace }}
      ca: {{ default "" .Values.model.temporal.ca }}
      cert: {{ default "" .Values.model.temporal.cert }}
      key: {{ default "" .Values.model.temporal.key }}
      serverName: {{ default "" .Values.model.temporal.serverName }}
    initmodel:
      path: {{ .Values.model.initModel.path }}
      enabled: {{ .Values.model.initModel.enabled }}
    log:
      external: {{ .Values.tags.observability }}
      otelcollector:
        host: {{ template "vdp.otel" . }}
        port: {{ template "vdp.otel.port" . }}
