name: Build and Push Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "examples/streamlit/**"

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Checks to see if the location of any files in the PR matches one of the listed folders.
      # We can use this filter to decide whether or not to build and push images.
      # You can check if a file with a listed file type is in the PR by doing:
      # if: ${{ steps.filter.outputs.streamlit-yolov7 == 'true' }}
      # This will return true if some file in 'examples/streamlit/yolov7' folder was changed
      # in the PR.
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            streamlit-yolov7:
              - 'examples/streamlit/yolov7/**'
            streamlit-instance-segmentation:
              - 'examples/streamlit/instance_segmentation/**'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: dropletbot
          password: ${{ secrets.botDockerHubPassword }}

      # Run only if some file in 'examples/streamlit/yolov7' folder was changed
      - name: Build and push (latest)
        uses: docker/build-push-action@v3
        if: steps.filter.outputs.streamlit-yolov7 == 'true'
        with:
          context: "{{defaultContext}}:examples/streamlit/yolov7"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: instill/streamlit-yolov7:latest
          no-cache: true

      # Run only if some file in 'examples/streamlit/instance_segmentation' folder was changed
      - name: Build and push (latest)
        uses: docker/build-push-action@v3
        if: steps.filter.outputs.streamlit-instance-segmentation == 'true'
        with:
          context: "{{defaultContext}}:examples/streamlit/instance_segmentation"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: instill/streamlit-instance-segmentation:latest
          no-cache: true
